name: terraform-apply

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ── Login a Azure (OIDC / SP JSON) ────────────────────────────────────
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ── Instala Terraform -------------------------------------------------
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      # ── Ejecuta Init + Apply ---------------------------------------------
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_INPUT: false # evita prompts interactivos
        run: terraform apply -auto-approve
