name: terraform-apply

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ─────────── Login a Azure ───────────
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ─────────── Exporta ARM_* ───────────
      - name: Set ARM env vars
        env:
          CREDS: ${{ secrets.AZURE_CREDENTIALS }}
        run: |
          echo "ARM_CLIENT_ID=$(echo $CREDS       | jq -r .clientId)"          >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(echo $CREDS   | jq -r .clientSecret)"      >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(echo $CREDS | jq -r .subscriptionId)"    >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(echo $CREDS       | jq -r .tenantId)"          >> $GITHUB_ENV

      # ─────────── Instala Terraform ───────────
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      # ─────────── Comandos TF ───────────
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          TF_INPUT: false
        run: terraform apply -auto-approve
