name: terraform-plan

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write # para OIDC
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ── Login a Azure con federated identity ──────────────────────────────
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ── Instala Terraform 1.7.5 en el runner ──────────────────────────────
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      # ── Comandos Terraform ------------------------------------------------
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      # ── Sube el artefacto del plan para revisión en el PR ────────────────
      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
